# ============================================================================
# 🚂 Railway Configuration - SIST_CABAÑAS_MVP Backend
# ============================================================================
#
# Configuración para despliegue en Railway.app
#
# Servicios necesarios:
#   1. Backend (FastAPI) - Este servicio
#   2. PostgreSQL 16 - Desde Railway Marketplace
#   3. Redis 7 - Desde Railway Marketplace
#
# Variables de entorno requeridas (configurar en Railway UI):
#   - DATABASE_URL (auto-generada por PostgreSQL plugin)
#   - REDIS_URL (auto-generada por Redis plugin)
#   - JWT_SECRET
#   - WHATSAPP_ACCESS_TOKEN, WHATSAPP_APP_SECRET, WHATSAPP_PHONE_ID, WHATSAPP_VERIFY_TOKEN
#   - MERCADOPAGO_ACCESS_TOKEN, MERCADOPAGO_WEBHOOK_SECRET
#   - ADMIN_ALLOWED_EMAILS
#   - ENVIRONMENT=production
#
# Docs: https://docs.railway.app/deploy/config-as-code
# ============================================================================

[build]
# Builder: Docker
builder = "DOCKERFILE"
# Dockerfile ubicado en backend/
dockerfilePath = "backend/Dockerfile"

[deploy]
# Start command (Railway ejecutará el CMD del Dockerfile)
# El CMD está definido en backend/Dockerfile como: /app/start.sh
startCommand = "/app/start.sh"

# Health check endpoint
healthcheckPath = "/api/v1/healthz"
healthcheckTimeout = 30

# Restart policy
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Service timeout (en segundos)
# 300 segundos = 5 minutos (para procesos de audio largo)
timeout = 300

[deploy.serviceConnect]
# Exponer el puerto 8000 (FastAPI)
expose = 8000
port = 8000

[env]
# Environment variables con valores por defecto
# (Railway permite sobrescribir en UI)
ENVIRONMENT = "production"
GUNICORN_WORKERS = "2"
GUNICORN_THREADS = "1"
GUNICORN_TIMEOUT = "120"
LOG_LEVEL = "info"
JWT_ALGORITHM = "HS256"
JWT_EXPIRATION_HOURS = "24"
ADMIN_TOKEN_EXPIRATION_HOURS = "168"
LOCK_TTL_SECONDS = "1800"
LOCK_RETRY_DELAY_MS = "100"
LOCK_MAX_RETRIES = "5"
RESERVATION_PRE_EXPIRY_MINUTES = "5"
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "60"
AUDIO_MAX_SIZE_MB = "25"
AUDIO_MIN_DURATION_SEC = "1"
AUDIO_MAX_DURATION_SEC = "300"
STT_CONFIDENCE_THRESHOLD = "0.7"
ICAL_EXPORT_TTL_DAYS = "365"
ICAL_SYNC_INTERVAL_MINUTES = "5"

# Variables sensibles (CONFIGURAR EN RAILWAY UI):
# - DATABASE_URL (auto from PostgreSQL plugin)
# - REDIS_URL (auto from Redis plugin)
# - JWT_SECRET
# - WHATSAPP_ACCESS_TOKEN
# - WHATSAPP_APP_SECRET
# - WHATSAPP_PHONE_ID
# - WHATSAPP_VERIFY_TOKEN
# - MERCADOPAGO_ACCESS_TOKEN
# - MERCADOPAGO_WEBHOOK_SECRET
# - ADMIN_ALLOWED_EMAILS
