version: '3.8'

services:
  app:
    build: .
    environment:
      - ENVIRONMENT=test
      - DATABASE_URL=postgresql+asyncpg://alojamientos_test:${POSTGRES_PASSWORD}@db:5432/alojamientos_test
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/1
      - WHATSAPP_ACCESS_TOKEN=dummy
      - WHATSAPP_APP_SECRET=dummy
      - MERCADOPAGO_ACCESS_TOKEN=dummy
      - JWT_SECRET=dev_jwt
      - ICS_SALT=dev_salt
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASS=
      - SMTP_FROM=reservas@example.com
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailhog:
        condition: service_started
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=alojamientos_test
      - POSTGRES_USER=alojamientos_test
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alojamientos_test -d alojamientos_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # UI

networks:
  default:
    name: alojamientos_test_net
