"""Add idempotency_keys table.

Revision ID: 005_idempotency_keys
Revises: 004_add_last_ical_sync_at
Create Date: 2025-01-10 22:30:00.000000

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "005_idempotency_keys"
down_revision = "004_add_last_ical_sync_at"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create idempotency_keys table with indexes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_keys",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("extra_metadata", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # Crear índices
    op.create_index("idx_idempotency_key_endpoint", "idempotency_keys", ["key", "endpoint"])
    op.create_index("idx_idempotency_expires", "idempotency_keys", ["expires_at"])
    op.create_index(
        op.f("ix_idempotency_keys_endpoint"), "idempotency_keys", ["endpoint"], unique=False
    )
    op.create_index(op.f("ix_idempotency_keys_key"), "idempotency_keys", ["key"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop idempotency_keys table and indexes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_idempotency_keys_key"), table_name="idempotency_keys")
    op.drop_index(op.f("ix_idempotency_keys_endpoint"), table_name="idempotency_keys")
    op.drop_index("idx_idempotency_expires", table_name="idempotency_keys")
    op.drop_index("idx_idempotency_key_endpoint", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    # ### end Alembic commands ###
